### ISSUE TITLE
AppImage Doesn't fully start on Manjaro Linux

### ISSUE THREAD

**Issue by clouwerman** [bangnokia/tinker2#6]
I downloaded the AppImage from your website and repo but whenever i try to start the application it loads for a second and then it closes

https://user-images.githubusercontent.com/74939867/140979957-44b45268-c70d-4cd9-8774-b59b80a44ea5.mp4

**Comment by bangnokia** [comment]
Thank you for your report the Linux problem. I will try to install Linux to investigate problem later because I mainly using MacOS and Windows :(

**Comment by clouwerman** [comment]
Just use Virtualbox or my personal favorite VMWare

Christiaan Louwerman
Back-end PHP Developer

E: ***@***.*** ***@***.***/0?redirect=mailto%3Achristiaan%40clouwerman.nl&recipient=cmVwbHkrQVIzWDNXMkNWTFI2V0JLU1MzSFNUS043UzJVUkxFVkJOSEhENUJHT1VFQHJlcGx5LmdpdGh1Yi5jb20%3D)
P: +31683225649 (tel:+31683225649)
W: https://clouwerman.nl ***@***.***/1?redirect=https%3A%2F%2Fclouwerman.nl&recipient=cmVwbHkrQVIzWDNXMkNWTFI2V0JLU1MzSFNUS043UzJVUkxFVkJOSEhENUJHT1VFQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by bangnokia** [comment]
@clouwerman unfortunately, this is currently a bug of build script. Here is the related issue https://github.com/tauri-apps/tauri/issues/2805

**Comment by bangnokia** [comment]
The only way is build it on a Arch or Manjaro distribution machine for now, but Github actions only supports ubuntu runner.

**Comment by clouwerman** [comment]
I will see if i can help you out with this issue and build an appimage for you or an alternative solution because the previous versions of your application have the same issue

**Comment by clouwerman** [comment]
Whenever i try to run the app i always get the same error.
![Screenshot 2021-11-10 at 10-35-22 React App](https://user-images.githubusercontent.com/74939867/141088165-e7d4b3f2-18f4-4843-8b07-1fd84e67da4a.png)

**Comment by clouwerman** [comment]
I have build the AppImage and you can test and run it.

https://cloud.solution4b.nl/index.php/s/RHdypPDywdCWxNP

**Comment by clouwerman** [comment]
If you keep me updated i will make a build for every version

**Comment by clouwerman** [comment]
I have build the AppImage and you can test and run it.

https://cloud.solution4b.nl/index.php/s/zqgM8zNiB4WpQKn

If you keep me updated i will make a build for every version

**Comment by bangnokia** [comment]
Thank you, that's great. I will upload your built to the latest release. Anyway this is Tauri App build problem, hopefully they fix it soon

**Comment by clouwerman** [comment]
I made the AppImage with Tauri

**Comment by clouwerman** [comment]
I made the AppImage with tauri, but never the less.

![image](https://user-images.githubusercontent.com/74939867/141173373-56094480-f9d9-48cd-a986-12e5af7bd95b.png)

**Comment by bangnokia** [comment]
that's looks sick on Manjaro UI ❤️. I updated download link to release and on the website. Will keep this issue open until we have solution to automate the build.

**Comment by clouwerman** [comment]
Just send me an email or add me to the repo when you need help

**Comment by clouwerman** [comment]
Just send me an email or add me to the repo when you have a new release i'm happy to help.
